services:
  bot:
    image: ghcr.io/kabo2468/oishii-bot
    build:
      context: .
      args:
        - GIT_SHA=unknown
    volumes:
      - ./config.json5:/app/config.json5:ro
      - ./valentine.json:/app/valentine.json:rw
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:alpine
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: db_password.secret
