[
    { emoji: '🍇', keywords: ['grapes'] },
    { emoji: '🍈', keywords: ['melon'] },
    { emoji: '🍉', keywords: ['watermelon'] },
    { emoji: '🍊', keywords: ['tangerine'] },
    { emoji: '🍋', keywords: ['lemon'] },
    { emoji: '🍌', keywords: ['banana'] },
    { emoji: '🍍', keywords: ['pineapple'] },
    { emoji: '🥭', keywords: ['mango'] },
    { emoji: '🍎', keywords: ['red apple'] },
    { emoji: '🍏', keywords: ['green apple'] },
    { emoji: '🍐', keywords: ['pear'] },
    { emoji: '🍑', keywords: ['peach'] },
    { emoji: '🍒', keywords: ['cherries'] },
    { emoji: '🍓', keywords: ['strawberry'] },
    { emoji: '🫐', keywords: ['blueberries'] },
    { emoji: '🥝', keywords: ['kiwi fruit'] },
    { emoji: '🍅', keywords: ['tomato'] },
    { emoji: '🫒', keywords: ['olive'] },
    { emoji: '🥥', keywords: ['coconut'] },
    { emoji: '🥑', keywords: ['avocado'] },
    { emoji: '🍆', keywords: ['eggplant'] },
    { emoji: '🥔', keywords: ['potato'] },
    { emoji: '🥕', keywords: ['carrot'] },
    { emoji: '🌽', keywords: ['ear of corn'] },
    { emoji: '🌶', keywords: ['hot pepper'] },
    { emoji: '🫑', keywords: ['bell pepper'] },
    { emoji: '🥒', keywords: ['cucumber'] },
    { emoji: '🥬', keywords: ['leafy green'] },
    { emoji: '🥦', keywords: ['broccoli'] },
    { emoji: '🧄', keywords: ['garlic'] },
    { emoji: '🧅', keywords: ['onion'] },
    { emoji: '🍄', keywords: ['mushroom'] },
    { emoji: '🥜', keywords: ['peanuts'] },
    { emoji: '🌰', keywords: ['chestnut'] },
    { emoji: '🍞', keywords: ['bread'] },
    { emoji: '🥐', keywords: ['croissant'] },
    { emoji: '🥖', keywords: ['baguette bread'] },
    { emoji: '🫓', keywords: ['flatbread'] },
    { emoji: '🥨', keywords: ['pretzel'] },
    { emoji: '🥯', keywords: ['bagel'] },
    { emoji: '🥞', keywords: ['pancakes'] },
    { emoji: '🧇', keywords: ['waffle'] },
    { emoji: '🧀', keywords: ['cheese wedge'] },
    { emoji: '🍖', keywords: ['meat on bone'] },
    { emoji: '🍗', keywords: ['poultry leg'] },
    { emoji: '🥩', keywords: ['cut of meat'] },
    { emoji: '🥓', keywords: ['bacon'] },
    { emoji: '🍔', keywords: ['hamburger'] },
    { emoji: '🍟', keywords: ['french fries'] },
    { emoji: '🍕', keywords: ['pizza'] },
    { emoji: '🌭', keywords: ['hot dog'] },
    { emoji: '🥪', keywords: ['sandwich'] },
    { emoji: '🌮', keywords: ['taco'] },
    { emoji: '🌯', keywords: ['burrito'] },
    { emoji: '🫔', keywords: ['tamale'] },
    { emoji: '🥙', keywords: ['stuffed flatbread'] },
    { emoji: '🧆', keywords: ['falafel'] },
    { emoji: '🥚', keywords: ['egg'] },
    { emoji: '🍳', keywords: ['cooking'] },
    { emoji: '🥘', keywords: ['shallow pan of food'] },
    { emoji: '🍲', keywords: ['pot of food'] },
    { emoji: '🫕', keywords: ['fondue'] },
    { emoji: '🥣', keywords: ['bowl with spoon'] },
    { emoji: '🥗', keywords: ['green salad'] },
    { emoji: '🍿', keywords: ['popcorn'] },
    { emoji: '🧈', keywords: ['butter'] },
    { emoji: '🧂', keywords: ['salt'] },
    { emoji: '🥫', keywords: ['canned food'] },
    { emoji: '🍱', keywords: ['bento box'] },
    { emoji: '🍘', keywords: ['rice cracker'] },
    { emoji: '🍙', keywords: ['rice ball'] },
    { emoji: '🍚', keywords: ['cooked rice'] },
    { emoji: '🍛', keywords: ['curry rice'] },
    { emoji: '🍜', keywords: ['steaming bowl'] },
    { emoji: '🍝', keywords: ['spaghetti'] },
    { emoji: '🍠', keywords: ['roasted sweet potato'] },
    { emoji: '🍢', keywords: ['oden'] },
    { emoji: '🍣', keywords: ['sushi'] },
    { emoji: '🍤', keywords: ['fried shrimp'] },
    { emoji: '🍥', keywords: ['fish cake with swirl'] },
    { emoji: '🥮', keywords: ['moon cake'] },
    { emoji: '🍡', keywords: ['dango'] },
    { emoji: '🥟', keywords: ['dumpling'] },
    { emoji: '🥠', keywords: ['fortune cookie'] },
    { emoji: '🥡', keywords: ['takeout box'] },
    { emoji: '🦀', keywords: ['crab'] },
    { emoji: '🦞', keywords: ['lobster'] },
    { emoji: '🦐', keywords: ['shrimp'] },
    { emoji: '🦑', keywords: ['squid'] },
    { emoji: '🦪', keywords: ['oyster'] },
    { emoji: '🍦', keywords: ['soft ice cream'] },
    { emoji: '🍧', keywords: ['shaved ice'] },
    { emoji: '🍨', keywords: ['ice cream'] },
    { emoji: '🍩', keywords: ['doughnut'] },
    { emoji: '🍪', keywords: ['cookie'] },
    { emoji: '🎂', keywords: ['birthday cake'] },
    { emoji: '🍰', keywords: ['shortcake'] },
    { emoji: '🧁', keywords: ['cupcake'] },
    { emoji: '🥧', keywords: ['pie'] },
    { emoji: '🍫', keywords: ['chocolate bar'] },
    { emoji: '🍬', keywords: ['candy'] },
    { emoji: '🍭', keywords: ['lollipop'] },
    { emoji: '🍮', keywords: ['custard'] },
    { emoji: '🍯', keywords: ['honey pot'] },
    { emoji: '🍼', keywords: ['baby bottle'] },
    { emoji: '🥛', keywords: ['glass of milk'] },
    { emoji: '☕', keywords: ['hot beverage'] },
    { emoji: '🫖', keywords: ['teapot'] },
    { emoji: '🍵', keywords: ['teacup without handle'] },
    { emoji: '🍶', keywords: ['sake'] },
    { emoji: '🍾', keywords: ['bottle with popping cork'] },
    { emoji: '🍷', keywords: ['wine glass'] },
    { emoji: '🍸', keywords: ['cocktail glass'] },
    { emoji: '🍹', keywords: ['tropical drink'] },
    { emoji: '🍺', keywords: ['beer mug'] },
    { emoji: '🍻', keywords: ['clinking beer mugs'] },
    { emoji: '🥂', keywords: ['clinking glasses'] },
    { emoji: '🥃', keywords: ['tumbler glass'] },
    { emoji: '🥤', keywords: ['cup with straw'] },
    { emoji: '🧋', keywords: ['bubble tea'] },
    { emoji: '🧃', keywords: ['beverage box'] },
    { emoji: '🧉', keywords: ['mate'] },
    { emoji: '🧊', keywords: ['ice'] },
    { emoji: '🥢', keywords: ['chopsticks'] },
    { emoji: '🍽', keywords: ['fork and knife with plate'] },
    { emoji: '🍴', keywords: ['fork and knife'] },
    { emoji: '🥄', keywords: ['spoon'] },
    { emoji: '🔪', keywords: ['kitchen knife'] },
    { emoji: '🏺', keywords: ['amphora'] },
];
